; Listing generated by Microsoft (R) Optimizing Compiler Version 19.00.24241.7 

include listing.inc

INCLUDELIB MSVCRT
INCLUDELIB OLDNAMES

PUBLIC	??0exception@std@@QEAA@AEBV01@@Z		; std::exception::exception
PUBLIC	??1exception@std@@UEAA@XZ			; std::exception::~exception
PUBLIC	?what@exception@std@@UEBAPEBDXZ			; std::exception::what
PUBLIC	??_Gexception@std@@UEAAPEAXI@Z			; std::exception::`scalar deleting destructor'
PUBLIC	??0logic_error@std@@QEAA@AEBV01@@Z		; std::logic_error::logic_error
PUBLIC	??_Glogic_error@std@@UEAAPEAXI@Z		; std::logic_error::`scalar deleting destructor'
PUBLIC	??1fail_fast@gsl@@UEAA@XZ			; gsl::fail_fast::~fail_fast
PUBLIC	??0fail_fast@gsl@@QEAA@AEBU01@@Z		; gsl::fail_fast::fail_fast
PUBLIC	??_Gfail_fast@gsl@@UEAAPEAXI@Z			; gsl::fail_fast::`scalar deleting destructor'
PUBLIC	??$throw_exception@Ufail_fast@gsl@@@details@gsl@@YAX$$QEAUfail_fast@1@@Z ; gsl::details::throw_exception<gsl::fail_fast>
PUBLIC	?foo@@YA_NXZ					; foo
PUBLIC	??_7exception@std@@6B@				; std::exception::`vftable'
PUBLIC	??_C@_0BC@EOODALEL@Unknown?5exception?$AA@	; `string'
PUBLIC	??_7logic_error@std@@6B@			; std::logic_error::`vftable'
PUBLIC	??_7fail_fast@gsl@@6B@				; gsl::fail_fast::`vftable'
PUBLIC	??_R0?AVexception@std@@@8			; std::exception `RTTI Type Descriptor'
PUBLIC	_CT??_R0?AVexception@std@@@8??0exception@std@@QEAA@AEBV01@@Z24
PUBLIC	_TI3?AUfail_fast@gsl@@
PUBLIC	_CTA3?AUfail_fast@gsl@@
PUBLIC	??_R0?AUfail_fast@gsl@@@8			; gsl::fail_fast `RTTI Type Descriptor'
PUBLIC	_CT??_R0?AUfail_fast@gsl@@@8??0fail_fast@gsl@@QEAA@AEBU01@@Z24
PUBLIC	??_R0?AVlogic_error@std@@@8			; std::logic_error `RTTI Type Descriptor'
PUBLIC	_CT??_R0?AVlogic_error@std@@@8??0logic_error@std@@QEAA@AEBV01@@Z24
PUBLIC	??_R4exception@std@@6B@				; std::exception::`RTTI Complete Object Locator'
PUBLIC	??_R3exception@std@@8				; std::exception::`RTTI Class Hierarchy Descriptor'
PUBLIC	??_R2exception@std@@8				; std::exception::`RTTI Base Class Array'
PUBLIC	??_R1A@?0A@EA@exception@std@@8			; std::exception::`RTTI Base Class Descriptor at (0,-1,0,64)'
PUBLIC	??_R4logic_error@std@@6B@			; std::logic_error::`RTTI Complete Object Locator'
PUBLIC	??_R3logic_error@std@@8				; std::logic_error::`RTTI Class Hierarchy Descriptor'
PUBLIC	??_R2logic_error@std@@8				; std::logic_error::`RTTI Base Class Array'
PUBLIC	??_R1A@?0A@EA@logic_error@std@@8		; std::logic_error::`RTTI Base Class Descriptor at (0,-1,0,64)'
PUBLIC	??_R4fail_fast@gsl@@6B@				; gsl::fail_fast::`RTTI Complete Object Locator'
PUBLIC	??_R3fail_fast@gsl@@8				; gsl::fail_fast::`RTTI Class Hierarchy Descriptor'
PUBLIC	??_R2fail_fast@gsl@@8				; gsl::fail_fast::`RTTI Base Class Array'
PUBLIC	??_R1A@?0A@EA@fail_fast@gsl@@8			; gsl::fail_fast::`RTTI Base Class Descriptor at (0,-1,0,64)'
EXTRN	??3@YAXPEAX_K@Z:PROC				; operator delete
EXTRN	__std_terminate:PROC
EXTRN	__imp___std_exception_copy:PROC
EXTRN	__imp___std_exception_destroy:PROC
EXTRN	??_Eexception@std@@UEAAPEAXI@Z:PROC		; std::exception::`vector deleting destructor'
EXTRN	??_Elogic_error@std@@UEAAPEAXI@Z:PROC		; std::logic_error::`vector deleting destructor'
EXTRN	??_Efail_fast@gsl@@UEAAPEAXI@Z:PROC		; gsl::fail_fast::`vector deleting destructor'
EXTRN	_CxxThrowException:PROC
EXTRN	__CxxFrameHandler3:PROC
EXTRN	??_7type_info@@6B@:BYTE				; type_info::`vftable'
;	COMDAT pdata
pdata	SEGMENT
$pdata$??0exception@std@@QEAA@QEBD@Z DD imagerel $LN4
	DD	imagerel $LN4+65
	DD	imagerel $unwind$??0exception@std@@QEAA@QEBD@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??0exception@std@@QEAA@AEBV01@@Z DD imagerel $LN4
	DD	imagerel $LN4+54
	DD	imagerel $unwind$??0exception@std@@QEAA@AEBV01@@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??_Gexception@std@@UEAAPEAXI@Z DD imagerel $LN8
	DD	imagerel $LN8+67
	DD	imagerel $unwind$??_Gexception@std@@UEAAPEAXI@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??0logic_error@std@@QEAA@PEBD@Z DD imagerel $LN7
	DD	imagerel $LN7+75
	DD	imagerel $unwind$??0logic_error@std@@QEAA@PEBD@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??0logic_error@std@@QEAA@AEBV01@@Z DD imagerel $LN6
	DD	imagerel $LN6+64
	DD	imagerel $unwind$??0logic_error@std@@QEAA@AEBV01@@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??0logic_error@std@@QEAA@$$QEAV01@@Z DD imagerel $LN6
	DD	imagerel $LN6+64
	DD	imagerel $unwind$??0logic_error@std@@QEAA@$$QEAV01@@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??_Glogic_error@std@@UEAAPEAXI@Z DD imagerel $LN11
	DD	imagerel $LN11+67
	DD	imagerel $unwind$??_Glogic_error@std@@UEAAPEAXI@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??0fail_fast@gsl@@QEAA@QEBD@Z DD imagerel $LN9
	DD	imagerel $LN9+75
	DD	imagerel $unwind$??0fail_fast@gsl@@QEAA@QEBD@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??0fail_fast@gsl@@QEAA@AEBU01@@Z DD imagerel $LN9
	DD	imagerel $LN9+64
	DD	imagerel $unwind$??0fail_fast@gsl@@QEAA@AEBU01@@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??0fail_fast@gsl@@QEAA@$$QEAU01@@Z DD imagerel $LN9
	DD	imagerel $LN9+64
	DD	imagerel $unwind$??0fail_fast@gsl@@QEAA@$$QEAU01@@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??_Gfail_fast@gsl@@UEAAPEAXI@Z DD imagerel $LN14
	DD	imagerel $LN14+67
	DD	imagerel $unwind$??_Gfail_fast@gsl@@UEAAPEAXI@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??$throw_exception@Ufail_fast@gsl@@@details@gsl@@YAX$$QEAUfail_fast@1@@Z DD imagerel $LN15
	DD	imagerel $LN15+73
	DD	imagerel $unwind$??$throw_exception@Ufail_fast@gsl@@@details@gsl@@YAX$$QEAUfail_fast@1@@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?foo@@YA_NXZ DD imagerel $LN150
	DD	imagerel $LN150+27
	DD	imagerel $unwind$?foo@@YA_NXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??$?0$0A@X@?$span@H$0?0@gsl@@QEAA@XZ DD imagerel $LN81
	DD	imagerel $LN81+33
	DD	imagerel $unwind$??$?0$0A@X@?$span@H$0?0@gsl@@QEAA@XZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??$?0$0A@X@?$span@$$CBH$0?0@gsl@@QEAA@XZ DD imagerel $LN81
	DD	imagerel $LN81+33
	DD	imagerel $unwind$??$?0$0A@X@?$span@$$CBH$0?0@gsl@@QEAA@XZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??$?0V?$extent_type@$0A@@details@gsl@@@?$storage_type@V?$extent_type@$0?0@details@gsl@@@?$span@H$0?0@gsl@@QEAA@PEAHV?$extent_type@$0A@@details@2@@Z DD imagerel $LN52
	DD	imagerel $LN52+33
	DD	imagerel $unwind$??$?0V?$extent_type@$0A@@details@gsl@@@?$storage_type@V?$extent_type@$0?0@details@gsl@@@?$span@H$0?0@gsl@@QEAA@PEAHV?$extent_type@$0A@@details@2@@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??$?0V?$extent_type@$0A@@details@gsl@@@?$storage_type@V?$extent_type@$0?0@details@gsl@@@?$span@$$CBH$0?0@gsl@@QEAA@PEBHV?$extent_type@$0A@@details@2@@Z DD imagerel $LN52
	DD	imagerel $LN52+33
	DD	imagerel $unwind$??$?0V?$extent_type@$0A@@details@gsl@@@?$storage_type@V?$extent_type@$0?0@details@gsl@@@?$span@$$CBH$0?0@gsl@@QEAA@PEBHV?$extent_type@$0A@@details@2@@Z
pdata	ENDS
;	COMDAT ??_R1A@?0A@EA@fail_fast@gsl@@8
rdata$r	SEGMENT
??_R1A@?0A@EA@fail_fast@gsl@@8 DD imagerel ??_R0?AUfail_fast@gsl@@@8 ; gsl::fail_fast::`RTTI Base Class Descriptor at (0,-1,0,64)'
	DD	02H
	DD	00H
	DD	0ffffffffH
	DD	00H
	DD	040H
	DD	imagerel ??_R3fail_fast@gsl@@8
rdata$r	ENDS
;	COMDAT ??_R2fail_fast@gsl@@8
rdata$r	SEGMENT
??_R2fail_fast@gsl@@8 DD imagerel ??_R1A@?0A@EA@fail_fast@gsl@@8 ; gsl::fail_fast::`RTTI Base Class Array'
	DD	imagerel ??_R1A@?0A@EA@logic_error@std@@8
	DD	imagerel ??_R1A@?0A@EA@exception@std@@8
	ORG $+3
rdata$r	ENDS
;	COMDAT ??_R3fail_fast@gsl@@8
rdata$r	SEGMENT
??_R3fail_fast@gsl@@8 DD 00H				; gsl::fail_fast::`RTTI Class Hierarchy Descriptor'
	DD	00H
	DD	03H
	DD	imagerel ??_R2fail_fast@gsl@@8
rdata$r	ENDS
;	COMDAT ??_R4fail_fast@gsl@@6B@
rdata$r	SEGMENT
??_R4fail_fast@gsl@@6B@ DD 01H				; gsl::fail_fast::`RTTI Complete Object Locator'
	DD	00H
	DD	00H
	DD	imagerel ??_R0?AUfail_fast@gsl@@@8
	DD	imagerel ??_R3fail_fast@gsl@@8
	DD	imagerel ??_R4fail_fast@gsl@@6B@
rdata$r	ENDS
;	COMDAT ??_R1A@?0A@EA@logic_error@std@@8
rdata$r	SEGMENT
??_R1A@?0A@EA@logic_error@std@@8 DD imagerel ??_R0?AVlogic_error@std@@@8 ; std::logic_error::`RTTI Base Class Descriptor at (0,-1,0,64)'
	DD	01H
	DD	00H
	DD	0ffffffffH
	DD	00H
	DD	040H
	DD	imagerel ??_R3logic_error@std@@8
rdata$r	ENDS
;	COMDAT ??_R2logic_error@std@@8
rdata$r	SEGMENT
??_R2logic_error@std@@8 DD imagerel ??_R1A@?0A@EA@logic_error@std@@8 ; std::logic_error::`RTTI Base Class Array'
	DD	imagerel ??_R1A@?0A@EA@exception@std@@8
	ORG $+3
rdata$r	ENDS
;	COMDAT ??_R3logic_error@std@@8
rdata$r	SEGMENT
??_R3logic_error@std@@8 DD 00H				; std::logic_error::`RTTI Class Hierarchy Descriptor'
	DD	00H
	DD	02H
	DD	imagerel ??_R2logic_error@std@@8
rdata$r	ENDS
;	COMDAT ??_R4logic_error@std@@6B@
rdata$r	SEGMENT
??_R4logic_error@std@@6B@ DD 01H			; std::logic_error::`RTTI Complete Object Locator'
	DD	00H
	DD	00H
	DD	imagerel ??_R0?AVlogic_error@std@@@8
	DD	imagerel ??_R3logic_error@std@@8
	DD	imagerel ??_R4logic_error@std@@6B@
rdata$r	ENDS
;	COMDAT ??_R1A@?0A@EA@exception@std@@8
rdata$r	SEGMENT
??_R1A@?0A@EA@exception@std@@8 DD imagerel ??_R0?AVexception@std@@@8 ; std::exception::`RTTI Base Class Descriptor at (0,-1,0,64)'
	DD	00H
	DD	00H
	DD	0ffffffffH
	DD	00H
	DD	040H
	DD	imagerel ??_R3exception@std@@8
rdata$r	ENDS
;	COMDAT ??_R2exception@std@@8
rdata$r	SEGMENT
??_R2exception@std@@8 DD imagerel ??_R1A@?0A@EA@exception@std@@8 ; std::exception::`RTTI Base Class Array'
	ORG $+3
rdata$r	ENDS
;	COMDAT ??_R3exception@std@@8
rdata$r	SEGMENT
??_R3exception@std@@8 DD 00H				; std::exception::`RTTI Class Hierarchy Descriptor'
	DD	00H
	DD	01H
	DD	imagerel ??_R2exception@std@@8
rdata$r	ENDS
;	COMDAT ??_R4exception@std@@6B@
rdata$r	SEGMENT
??_R4exception@std@@6B@ DD 01H				; std::exception::`RTTI Complete Object Locator'
	DD	00H
	DD	00H
	DD	imagerel ??_R0?AVexception@std@@@8
	DD	imagerel ??_R3exception@std@@8
	DD	imagerel ??_R4exception@std@@6B@
rdata$r	ENDS
;	COMDAT _CT??_R0?AVlogic_error@std@@@8??0logic_error@std@@QEAA@AEBV01@@Z24
xdata$x	SEGMENT
_CT??_R0?AVlogic_error@std@@@8??0logic_error@std@@QEAA@AEBV01@@Z24 DD 00H
	DD	imagerel ??_R0?AVlogic_error@std@@@8
	DD	00H
	DD	0ffffffffH
	ORG $+4
	DD	018H
	DD	imagerel ??0logic_error@std@@QEAA@AEBV01@@Z
xdata$x	ENDS
;	COMDAT ??_R0?AVlogic_error@std@@@8
data$r	SEGMENT
??_R0?AVlogic_error@std@@@8 DQ FLAT:??_7type_info@@6B@	; std::logic_error `RTTI Type Descriptor'
	DQ	0000000000000000H
	DB	'.?AVlogic_error@std@@', 00H
data$r	ENDS
;	COMDAT _CT??_R0?AUfail_fast@gsl@@@8??0fail_fast@gsl@@QEAA@AEBU01@@Z24
xdata$x	SEGMENT
_CT??_R0?AUfail_fast@gsl@@@8??0fail_fast@gsl@@QEAA@AEBU01@@Z24 DD 00H
	DD	imagerel ??_R0?AUfail_fast@gsl@@@8
	DD	00H
	DD	0ffffffffH
	ORG $+4
	DD	018H
	DD	imagerel ??0fail_fast@gsl@@QEAA@AEBU01@@Z
xdata$x	ENDS
;	COMDAT ??_R0?AUfail_fast@gsl@@@8
data$r	SEGMENT
??_R0?AUfail_fast@gsl@@@8 DQ FLAT:??_7type_info@@6B@	; gsl::fail_fast `RTTI Type Descriptor'
	DQ	0000000000000000H
	DB	'.?AUfail_fast@gsl@@', 00H
data$r	ENDS
;	COMDAT _CTA3?AUfail_fast@gsl@@
xdata$x	SEGMENT
_CTA3?AUfail_fast@gsl@@ DD 03H
	DD	imagerel _CT??_R0?AUfail_fast@gsl@@@8??0fail_fast@gsl@@QEAA@AEBU01@@Z24
	DD	imagerel _CT??_R0?AVlogic_error@std@@@8??0logic_error@std@@QEAA@AEBV01@@Z24
	DD	imagerel _CT??_R0?AVexception@std@@@8??0exception@std@@QEAA@AEBV01@@Z24
xdata$x	ENDS
;	COMDAT _TI3?AUfail_fast@gsl@@
xdata$x	SEGMENT
_TI3?AUfail_fast@gsl@@ DD 00H
	DD	imagerel ??1fail_fast@gsl@@UEAA@XZ
	DD	00H
	DD	imagerel _CTA3?AUfail_fast@gsl@@
xdata$x	ENDS
;	COMDAT _CT??_R0?AVexception@std@@@8??0exception@std@@QEAA@AEBV01@@Z24
xdata$x	SEGMENT
_CT??_R0?AVexception@std@@@8??0exception@std@@QEAA@AEBV01@@Z24 DD 00H
	DD	imagerel ??_R0?AVexception@std@@@8
	DD	00H
	DD	0ffffffffH
	ORG $+4
	DD	018H
	DD	imagerel ??0exception@std@@QEAA@AEBV01@@Z
xdata$x	ENDS
;	COMDAT ??_R0?AVexception@std@@@8
data$r	SEGMENT
??_R0?AVexception@std@@@8 DQ FLAT:??_7type_info@@6B@	; std::exception `RTTI Type Descriptor'
	DQ	0000000000000000H
	DB	'.?AVexception@std@@', 00H
data$r	ENDS
;	COMDAT ??_7fail_fast@gsl@@6B@
CONST	SEGMENT
??_7fail_fast@gsl@@6B@ DQ FLAT:??_R4fail_fast@gsl@@6B@	; gsl::fail_fast::`vftable'
	DQ	FLAT:??_Efail_fast@gsl@@UEAAPEAXI@Z
	DQ	FLAT:?what@exception@std@@UEBAPEBDXZ
CONST	ENDS
;	COMDAT ??_7logic_error@std@@6B@
CONST	SEGMENT
??_7logic_error@std@@6B@ DQ FLAT:??_R4logic_error@std@@6B@ ; std::logic_error::`vftable'
	DQ	FLAT:??_Elogic_error@std@@UEAAPEAXI@Z
	DQ	FLAT:?what@exception@std@@UEBAPEBDXZ
CONST	ENDS
;	COMDAT ??_C@_0BC@EOODALEL@Unknown?5exception?$AA@
CONST	SEGMENT
??_C@_0BC@EOODALEL@Unknown?5exception?$AA@ DB 'Unknown exception', 00H ; `string'
CONST	ENDS
;	COMDAT ??_7exception@std@@6B@
CONST	SEGMENT
??_7exception@std@@6B@ DQ FLAT:??_R4exception@std@@6B@	; std::exception::`vftable'
	DQ	FLAT:??_Eexception@std@@UEAAPEAXI@Z
	DQ	FLAT:?what@exception@std@@UEBAPEBDXZ
CONST	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??$?0V?$extent_type@$0A@@details@gsl@@@?$storage_type@V?$extent_type@$0?0@details@gsl@@@?$span@$$CBH$0?0@gsl@@QEAA@PEBHV?$extent_type@$0A@@details@2@@Z DD 010c01H
	DD	02204H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??$?0V?$extent_type@$0A@@details@gsl@@@?$storage_type@V?$extent_type@$0?0@details@gsl@@@?$span@H$0?0@gsl@@QEAA@PEAHV?$extent_type@$0A@@details@2@@Z DD 010c01H
	DD	02204H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$ip2state$??$?0$0A@X@?$span@$$CBH$0?0@gsl@@QEAA@XZ DD imagerel ??$?0$0A@X@?$span@$$CBH$0?0@gsl@@QEAA@XZ
	DD	0ffffffffH
xdata	ENDS
;	COMDAT CONST
CONST	SEGMENT
$cppxdata$??$?0$0A@X@?$span@$$CBH$0?0@gsl@@QEAA@XZ DD 019930522H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	01H
	DD	imagerel $ip2state$??$?0$0A@X@?$span@$$CBH$0?0@gsl@@QEAA@XZ
	DD	00H
	DD	00H
	DD	05H
CONST	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??$?0$0A@X@?$span@$$CBH$0?0@gsl@@QEAA@XZ DD 010c19H
	DD	02204H
	DD	imagerel __CxxFrameHandler3
	DD	imagerel $cppxdata$??$?0$0A@X@?$span@$$CBH$0?0@gsl@@QEAA@XZ
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$ip2state$??$?0$0A@X@?$span@H$0?0@gsl@@QEAA@XZ DD imagerel ??$?0$0A@X@?$span@H$0?0@gsl@@QEAA@XZ
	DD	0ffffffffH
xdata	ENDS
;	COMDAT CONST
CONST	SEGMENT
$cppxdata$??$?0$0A@X@?$span@H$0?0@gsl@@QEAA@XZ DD 019930522H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	01H
	DD	imagerel $ip2state$??$?0$0A@X@?$span@H$0?0@gsl@@QEAA@XZ
	DD	00H
	DD	00H
	DD	05H
CONST	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??$?0$0A@X@?$span@H$0?0@gsl@@QEAA@XZ DD 010c19H
	DD	02204H
	DD	imagerel __CxxFrameHandler3
	DD	imagerel $cppxdata$??$?0$0A@X@?$span@H$0?0@gsl@@QEAA@XZ
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$ip2state$?foo@@YA_NXZ DD imagerel ?foo@@YA_NXZ
	DD	0ffffffffH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$stateUnwindMap$?foo@@YA_NXZ DD 0ffffffffH
	DD	imagerel __std_terminate
xdata	ENDS
;	COMDAT CONST
CONST	SEGMENT
$cppxdata$?foo@@YA_NXZ DD 019930522H
	DD	01H
	DD	imagerel $stateUnwindMap$?foo@@YA_NXZ
	DD	00H
	DD	00H
	DD	01H
	DD	imagerel $ip2state$?foo@@YA_NXZ
	DD	00H
	DD	00H
	DD	01H
CONST	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?foo@@YA_NXZ DD 010c11H
	DD	02204H
	DD	imagerel __CxxFrameHandler3
	DD	imagerel $cppxdata$?foo@@YA_NXZ
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??$throw_exception@Ufail_fast@gsl@@@details@gsl@@YAX$$QEAUfail_fast@1@@Z DD 010401H
	DD	08204H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??_Gfail_fast@gsl@@UEAAPEAXI@Z DD 040a01H
	DD	06340aH
	DD	07006320aH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??0fail_fast@gsl@@QEAA@$$QEAU01@@Z DD 020601H
	DD	030023206H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??0fail_fast@gsl@@QEAA@AEBU01@@Z DD 020601H
	DD	030023206H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??0fail_fast@gsl@@QEAA@QEBD@Z DD 020601H
	DD	030025206H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??_Glogic_error@std@@UEAAPEAXI@Z DD 040a01H
	DD	06340aH
	DD	07006320aH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??0logic_error@std@@QEAA@$$QEAV01@@Z DD 020601H
	DD	030023206H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??0logic_error@std@@QEAA@AEBV01@@Z DD 020601H
	DD	030023206H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??0logic_error@std@@QEAA@PEBD@Z DD 020601H
	DD	030025206H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??_Gexception@std@@UEAAPEAXI@Z DD 040a01H
	DD	06340aH
	DD	07006320aH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??0exception@std@@QEAA@AEBV01@@Z DD 020601H
	DD	030023206H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??0exception@std@@QEAA@QEBD@Z DD 020601H
	DD	030025206H
xdata	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??$?0$0A@@?$extent_type@$0?0@details@gsl@@QEAA@V?$extent_type@$0A@@12@@Z
_TEXT	SEGMENT
this$ = 8
ext$ = 16
??$?0$0A@@?$extent_type@$0?0@details@gsl@@QEAA@V?$extent_type@$0A@@12@@Z PROC ; gsl::details::extent_type<-1>::extent_type<-1><0>, COMDAT
; File c:\projects\gsl\include\gsl\span
; Line 333
	mov	QWORD PTR [rcx], 0
; Line 334
	mov	rax, rcx
	ret	0
??$?0$0A@@?$extent_type@$0?0@details@gsl@@QEAA@V?$extent_type@$0A@@12@@Z ENDP ; gsl::details::extent_type<-1>::extent_type<-1><0>
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??$?0V?$extent_type@$0A@@details@gsl@@@?$storage_type@V?$extent_type@$0?0@details@gsl@@@?$span@$$CBH$0?0@gsl@@QEAA@PEBHV?$extent_type@$0A@@details@2@@Z
_TEXT	SEGMENT
$T1 = 0
this$ = 32
data$ = 40
$T2 = 48
ext$ = 48
??$?0V?$extent_type@$0A@@details@gsl@@@?$storage_type@V?$extent_type@$0?0@details@gsl@@@?$span@$$CBH$0?0@gsl@@QEAA@PEBHV?$extent_type@$0A@@details@2@@Z PROC ; gsl::span<int const ,-1>::storage_type<gsl::details::extent_type<-1> >::storage_type<gsl::details::extent_type<-1> ><gsl::details::extent_type<0> >, COMDAT
; File c:\projects\gsl\include\gsl\span
; Line 597
$LN52:
	sub	rsp, 24
	mov	QWORD PTR $T1[rsp], -2
	xor	eax, eax
	mov	DWORD PTR $T2[rsp], eax
; Line 333
	mov	QWORD PTR [rcx], rax
; Line 596
	mov	QWORD PTR [rcx+8], rdx
; Line 600
	mov	rax, rcx
	add	rsp, 24
	ret	0
??$?0V?$extent_type@$0A@@details@gsl@@@?$storage_type@V?$extent_type@$0?0@details@gsl@@@?$span@$$CBH$0?0@gsl@@QEAA@PEBHV?$extent_type@$0A@@details@2@@Z ENDP ; gsl::span<int const ,-1>::storage_type<gsl::details::extent_type<-1> >::storage_type<gsl::details::extent_type<-1> ><gsl::details::extent_type<0> >
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??$?0V?$extent_type@$0A@@details@gsl@@@?$storage_type@V?$extent_type@$0?0@details@gsl@@@?$span@H$0?0@gsl@@QEAA@PEAHV?$extent_type@$0A@@details@2@@Z
_TEXT	SEGMENT
$T1 = 0
this$ = 32
data$ = 40
$T2 = 48
ext$ = 48
??$?0V?$extent_type@$0A@@details@gsl@@@?$storage_type@V?$extent_type@$0?0@details@gsl@@@?$span@H$0?0@gsl@@QEAA@PEAHV?$extent_type@$0A@@details@2@@Z PROC ; gsl::span<int,-1>::storage_type<gsl::details::extent_type<-1> >::storage_type<gsl::details::extent_type<-1> ><gsl::details::extent_type<0> >, COMDAT
; File c:\projects\gsl\include\gsl\span
; Line 597
$LN52:
	sub	rsp, 24
	mov	QWORD PTR $T1[rsp], -2
	xor	eax, eax
	mov	DWORD PTR $T2[rsp], eax
; Line 333
	mov	QWORD PTR [rcx], rax
; Line 596
	mov	QWORD PTR [rcx+8], rdx
; Line 600
	mov	rax, rcx
	add	rsp, 24
	ret	0
??$?0V?$extent_type@$0A@@details@gsl@@@?$storage_type@V?$extent_type@$0?0@details@gsl@@@?$span@H$0?0@gsl@@QEAA@PEAHV?$extent_type@$0A@@details@2@@Z ENDP ; gsl::span<int,-1>::storage_type<gsl::details::extent_type<-1> >::storage_type<gsl::details::extent_type<-1> ><gsl::details::extent_type<0> >
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?size@?$extent_type@$0A@@details@gsl@@QEBA_JXZ
_TEXT	SEGMENT
this$ = 8
?size@?$extent_type@$0A@@details@gsl@@QEBA_JXZ PROC	; gsl::details::extent_type<0>::size, COMDAT
; File c:\projects\gsl\include\gsl\span
; Line 323
	xor	eax, eax
	ret	0
?size@?$extent_type@$0A@@details@gsl@@QEBA_JXZ ENDP	; gsl::details::extent_type<0>::size
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??0?$extent_type@$0A@@details@gsl@@QEAA@XZ
_TEXT	SEGMENT
this$ = 8
??0?$extent_type@$0A@@details@gsl@@QEAA@XZ PROC		; gsl::details::extent_type<0>::extent_type<0>, COMDAT
; File c:\projects\gsl\include\gsl\span
; Line 311
	mov	rax, rcx
	ret	0
??0?$extent_type@$0A@@details@gsl@@QEAA@XZ ENDP		; gsl::details::extent_type<0>::extent_type<0>
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??$forward@Ufail_fast@gsl@@@std@@YA$$QEAUfail_fast@gsl@@AEAU12@@Z
_TEXT	SEGMENT
_Arg$ = 8
??$forward@Ufail_fast@gsl@@@std@@YA$$QEAUfail_fast@gsl@@AEAU12@@Z PROC ; std::forward<gsl::fail_fast>, COMDAT
; File c:\program files (x86)\microsoft visual studio 14.0\vc\include\type_traits
; Line 1276
	mov	rax, rcx
; Line 1277
	ret	0
??$forward@Ufail_fast@gsl@@@std@@YA$$QEAUfail_fast@gsl@@AEAU12@@Z ENDP ; std::forward<gsl::fail_fast>
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??$?0$0A@X@?$span@$$CBH$0?0@gsl@@QEAA@XZ
_TEXT	SEGMENT
$T1 = 0
$T2 = 32
this$ = 32
??$?0$0A@X@?$span@$$CBH$0?0@gsl@@QEAA@XZ PROC		; gsl::span<int const ,-1>::span<int const ,-1><0,void>, COMDAT
; File c:\projects\gsl\include\gsl\span
; Line 384
$LN81:
	sub	rsp, 24
	mov	QWORD PTR $T1[rsp], -2
	xor	eax, eax
	mov	DWORD PTR $T2[rsp], eax
; Line 333
	mov	QWORD PTR [rcx], rax
; Line 596
	mov	QWORD PTR [rcx+8], rax
; Line 384
	mov	rax, rcx
	add	rsp, 24
	ret	0
??$?0$0A@X@?$span@$$CBH$0?0@gsl@@QEAA@XZ ENDP		; gsl::span<int const ,-1>::span<int const ,-1><0,void>
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?data@?$storage_type@V?$extent_type@$0?0@details@gsl@@@?$span@$$CBH$0?0@gsl@@QEBAPEBHXZ
_TEXT	SEGMENT
this$ = 8
?data@?$storage_type@V?$extent_type@$0?0@details@gsl@@@?$span@$$CBH$0?0@gsl@@QEBAPEBHXZ PROC ; gsl::span<int const ,-1>::storage_type<gsl::details::extent_type<-1> >::data, COMDAT
; File c:\projects\gsl\include\gsl\span
; Line 602
	mov	rax, QWORD PTR [rcx+8]
	ret	0
?data@?$storage_type@V?$extent_type@$0?0@details@gsl@@@?$span@$$CBH$0?0@gsl@@QEBAPEBHXZ ENDP ; gsl::span<int const ,-1>::storage_type<gsl::details::extent_type<-1> >::data
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?data@?$span@$$CBH$0?0@gsl@@QEBAPEBHXZ
_TEXT	SEGMENT
this$ = 8
?data@?$span@$$CBH$0?0@gsl@@QEBAPEBHXZ PROC		; gsl::span<int const ,-1>::data, COMDAT
; File c:\projects\gsl\include\gsl\span
; Line 515
	mov	rax, QWORD PTR [rcx+8]
	ret	0
?data@?$span@$$CBH$0?0@gsl@@QEBAPEBHXZ ENDP		; gsl::span<int const ,-1>::data
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?size@?$span@$$CBH$0?0@gsl@@QEBA_JXZ
_TEXT	SEGMENT
this$ = 8
?size@?$span@$$CBH$0?0@gsl@@QEBA_JXZ PROC		; gsl::span<int const ,-1>::size, COMDAT
; File c:\projects\gsl\include\gsl\span
; Line 498
	mov	rax, QWORD PTR [rcx]
	ret	0
?size@?$span@$$CBH$0?0@gsl@@QEBA_JXZ ENDP		; gsl::span<int const ,-1>::size
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??$?0$0A@X@?$span@H$0?0@gsl@@QEAA@XZ
_TEXT	SEGMENT
$T1 = 0
$T2 = 32
this$ = 32
??$?0$0A@X@?$span@H$0?0@gsl@@QEAA@XZ PROC		; gsl::span<int,-1>::span<int,-1><0,void>, COMDAT
; File c:\projects\gsl\include\gsl\span
; Line 384
$LN81:
	sub	rsp, 24
	mov	QWORD PTR $T1[rsp], -2
	xor	eax, eax
	mov	DWORD PTR $T2[rsp], eax
; Line 333
	mov	QWORD PTR [rcx], rax
; Line 596
	mov	QWORD PTR [rcx+8], rax
; Line 384
	mov	rax, rcx
	add	rsp, 24
	ret	0
??$?0$0A@X@?$span@H$0?0@gsl@@QEAA@XZ ENDP		; gsl::span<int,-1>::span<int,-1><0,void>
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?data@?$storage_type@V?$extent_type@$0?0@details@gsl@@@?$span@H$0?0@gsl@@QEBAPEAHXZ
_TEXT	SEGMENT
this$ = 8
?data@?$storage_type@V?$extent_type@$0?0@details@gsl@@@?$span@H$0?0@gsl@@QEBAPEAHXZ PROC ; gsl::span<int,-1>::storage_type<gsl::details::extent_type<-1> >::data, COMDAT
; File c:\projects\gsl\include\gsl\span
; Line 602
	mov	rax, QWORD PTR [rcx+8]
	ret	0
?data@?$storage_type@V?$extent_type@$0?0@details@gsl@@@?$span@H$0?0@gsl@@QEBAPEAHXZ ENDP ; gsl::span<int,-1>::storage_type<gsl::details::extent_type<-1> >::data
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?data@?$span@H$0?0@gsl@@QEBAPEAHXZ
_TEXT	SEGMENT
this$ = 8
?data@?$span@H$0?0@gsl@@QEBAPEAHXZ PROC			; gsl::span<int,-1>::data, COMDAT
; File c:\projects\gsl\include\gsl\span
; Line 515
	mov	rax, QWORD PTR [rcx+8]
	ret	0
?data@?$span@H$0?0@gsl@@QEBAPEAHXZ ENDP			; gsl::span<int,-1>::data
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?size@?$span@H$0?0@gsl@@QEBA_JXZ
_TEXT	SEGMENT
this$ = 8
?size@?$span@H$0?0@gsl@@QEBA_JXZ PROC			; gsl::span<int,-1>::size, COMDAT
; File c:\projects\gsl\include\gsl\span
; Line 498
	mov	rax, QWORD PTR [rcx]
	ret	0
?size@?$span@H$0?0@gsl@@QEBA_JXZ ENDP			; gsl::span<int,-1>::size
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?foo@@YA_NXZ
_TEXT	SEGMENT
$T1 = 0
$T2 = 32
?foo@@YA_NXZ PROC					; foo, COMDAT
; File c:\projects\gsl\tests\span_compile_only.cpp
; Line 42
$LN150:
	sub	rsp, 24
	mov	QWORD PTR $T1[rsp], -2
	mov	DWORD PTR $T2[rsp], 0
; Line 51
	mov	al, 1
; Line 53
	add	rsp, 24
	ret	0
?foo@@YA_NXZ ENDP					; foo
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??$throw_exception@Ufail_fast@gsl@@@details@gsl@@YAX$$QEAUfail_fast@1@@Z
_TEXT	SEGMENT
$T1 = 32
exception$ = 80
??$throw_exception@Ufail_fast@gsl@@@details@gsl@@YAX$$QEAUfail_fast@1@@Z PROC ; gsl::details::throw_exception<gsl::fail_fast>, COMDAT
; File c:\projects\gsl\include\gsl\gsl_assert
; Line 143
$LN15:
	sub	rsp, 72					; 00000048H
; File c:\program files (x86)\microsoft visual studio 14.0\vc\include\vcruntime_exception.h
; Line 66
	lea	rax, OFFSET FLAT:??_7exception@std@@6B@
; Line 67
	add	rcx, 8
	mov	QWORD PTR $T1[rsp], rax
	lea	rdx, QWORD PTR $T1[rsp+8]
	xor	eax, eax
	mov	QWORD PTR $T1[rsp+8], rax
	mov	QWORD PTR $T1[rsp+16], rax
	call	QWORD PTR __imp___std_exception_copy
	lea	rax, OFFSET FLAT:??_7fail_fast@gsl@@6B@
; File c:\projects\gsl\include\gsl\gsl_assert
; Line 144
	lea	rdx, OFFSET FLAT:_TI3?AUfail_fast@gsl@@
	mov	QWORD PTR $T1[rsp], rax
	lea	rcx, QWORD PTR $T1[rsp]
	call	_CxxThrowException
	int	3
$LN14@throw_exce:
??$throw_exception@Ufail_fast@gsl@@@details@gsl@@YAX$$QEAUfail_fast@1@@Z ENDP ; gsl::details::throw_exception<gsl::fail_fast>
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?size@?$extent_type@$0?0@details@gsl@@QEBA_JXZ
_TEXT	SEGMENT
this$ = 8
?size@?$extent_type@$0?0@details@gsl@@QEBA_JXZ PROC	; gsl::details::extent_type<-1>::size, COMDAT
; File c:\projects\gsl\include\gsl\span
; Line 338
	mov	rax, QWORD PTR [rcx]
	ret	0
?size@?$extent_type@$0?0@details@gsl@@QEBA_JXZ ENDP	; gsl::details::extent_type<-1>::size
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??_Gfail_fast@gsl@@UEAAPEAXI@Z
_TEXT	SEGMENT
this$ = 48
__flags$ = 56
??_Gfail_fast@gsl@@UEAAPEAXI@Z PROC			; gsl::fail_fast::`scalar deleting destructor', COMDAT
$LN14:
	mov	QWORD PTR [rsp+8], rbx
	push	rdi
	sub	rsp, 32					; 00000020H
; File c:\program files (x86)\microsoft visual studio 14.0\vc\include\vcruntime_exception.h
; Line 83
	lea	rax, OFFSET FLAT:??_7exception@std@@6B@
	mov	rdi, rcx
	mov	QWORD PTR [rcx], rax
	mov	ebx, edx
; Line 84
	add	rcx, 8
	call	QWORD PTR __imp___std_exception_destroy
	test	bl, 1
	je	SHORT $LN12@scalar
	mov	edx, 24
	mov	rcx, rdi
	call	??3@YAXPEAX_K@Z				; operator delete
$LN12@scalar:
	mov	rax, rdi
	mov	rbx, QWORD PTR [rsp+48]
	add	rsp, 32					; 00000020H
	pop	rdi
	ret	0
??_Gfail_fast@gsl@@UEAAPEAXI@Z ENDP			; gsl::fail_fast::`scalar deleting destructor'
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??0fail_fast@gsl@@QEAA@$$QEAU01@@Z
_TEXT	SEGMENT
this$ = 48
__that$ = 56
??0fail_fast@gsl@@QEAA@$$QEAU01@@Z PROC			; gsl::fail_fast::fail_fast, COMDAT
$LN9:
	push	rbx
	sub	rsp, 32					; 00000020H
	mov	rbx, rcx
	mov	rax, rdx
; File c:\program files (x86)\microsoft visual studio 14.0\vc\include\vcruntime_exception.h
; Line 65
	lea	rdx, QWORD PTR [rbx+8]
; Line 66
	lea	rcx, OFFSET FLAT:??_7exception@std@@6B@
	mov	QWORD PTR [rbx], rcx
	xor	ecx, ecx
	mov	QWORD PTR [rdx], rcx
	mov	QWORD PTR [rdx+8], rcx
; Line 67
	lea	rcx, QWORD PTR [rax+8]
	call	QWORD PTR __imp___std_exception_copy
	lea	rax, OFFSET FLAT:??_7fail_fast@gsl@@6B@
	mov	QWORD PTR [rbx], rax
	mov	rax, rbx
	add	rsp, 32					; 00000020H
	pop	rbx
	ret	0
??0fail_fast@gsl@@QEAA@$$QEAU01@@Z ENDP			; gsl::fail_fast::fail_fast
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??0fail_fast@gsl@@QEAA@AEBU01@@Z
_TEXT	SEGMENT
this$ = 48
__that$ = 56
??0fail_fast@gsl@@QEAA@AEBU01@@Z PROC			; gsl::fail_fast::fail_fast, COMDAT
$LN9:
	push	rbx
	sub	rsp, 32					; 00000020H
	mov	rbx, rcx
	mov	rax, rdx
; File c:\program files (x86)\microsoft visual studio 14.0\vc\include\vcruntime_exception.h
; Line 65
	lea	rdx, QWORD PTR [rbx+8]
; Line 66
	lea	rcx, OFFSET FLAT:??_7exception@std@@6B@
	mov	QWORD PTR [rbx], rcx
	xor	ecx, ecx
	mov	QWORD PTR [rdx], rcx
	mov	QWORD PTR [rdx+8], rcx
; Line 67
	lea	rcx, QWORD PTR [rax+8]
	call	QWORD PTR __imp___std_exception_copy
	lea	rax, OFFSET FLAT:??_7fail_fast@gsl@@6B@
	mov	QWORD PTR [rbx], rax
	mov	rax, rbx
	add	rsp, 32					; 00000020H
	pop	rbx
	ret	0
??0fail_fast@gsl@@QEAA@AEBU01@@Z ENDP			; gsl::fail_fast::fail_fast
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??1fail_fast@gsl@@UEAA@XZ
_TEXT	SEGMENT
this$ = 8
??1fail_fast@gsl@@UEAA@XZ PROC				; gsl::fail_fast::~fail_fast, COMDAT
; File c:\program files (x86)\microsoft visual studio 14.0\vc\include\vcruntime_exception.h
; Line 83
	lea	rax, OFFSET FLAT:??_7exception@std@@6B@
	mov	QWORD PTR [rcx], rax
; Line 84
	add	rcx, 8
	rex_jmp	QWORD PTR __imp___std_exception_destroy
??1fail_fast@gsl@@UEAA@XZ ENDP				; gsl::fail_fast::~fail_fast
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??0fail_fast@gsl@@QEAA@QEBD@Z
_TEXT	SEGMENT
_InitData$1 = 32
this$ = 64
message$ = 72
??0fail_fast@gsl@@QEAA@QEBD@Z PROC			; gsl::fail_fast::fail_fast, COMDAT
; File c:\projects\gsl\include\gsl\gsl_assert
; Line 99
$LN9:
	push	rbx
	sub	rsp, 48					; 00000030H
	mov	rbx, rcx
; File c:\program files (x86)\microsoft visual studio 14.0\vc\include\vcruntime_exception.h
; Line 54
	mov	BYTE PTR _InitData$1[rsp+8], 1
; File c:\projects\gsl\include\gsl\gsl_assert
; Line 99
	mov	rax, rdx
; File c:\program files (x86)\microsoft visual studio 14.0\vc\include\vcruntime_exception.h
; Line 53
	lea	rcx, OFFSET FLAT:??_7exception@std@@6B@
	lea	rdx, QWORD PTR [rbx+8]
; Line 54
	mov	QWORD PTR _InitData$1[rsp], rax
	mov	QWORD PTR [rbx], rcx
	xor	ecx, ecx
	mov	QWORD PTR [rdx], rcx
	mov	QWORD PTR [rdx+8], rcx
; Line 55
	lea	rcx, QWORD PTR _InitData$1[rsp]
	call	QWORD PTR __imp___std_exception_copy
; File c:\projects\gsl\include\gsl\gsl_assert
; Line 99
	lea	rax, OFFSET FLAT:??_7fail_fast@gsl@@6B@
	mov	QWORD PTR [rbx], rax
	mov	rax, rbx
	add	rsp, 48					; 00000030H
	pop	rbx
	ret	0
??0fail_fast@gsl@@QEAA@QEBD@Z ENDP			; gsl::fail_fast::fail_fast
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??_Glogic_error@std@@UEAAPEAXI@Z
_TEXT	SEGMENT
this$ = 48
__flags$ = 56
??_Glogic_error@std@@UEAAPEAXI@Z PROC			; std::logic_error::`scalar deleting destructor', COMDAT
$LN11:
	mov	QWORD PTR [rsp+8], rbx
	push	rdi
	sub	rsp, 32					; 00000020H
; File c:\program files (x86)\microsoft visual studio 14.0\vc\include\vcruntime_exception.h
; Line 83
	lea	rax, OFFSET FLAT:??_7exception@std@@6B@
	mov	rdi, rcx
	mov	QWORD PTR [rcx], rax
	mov	ebx, edx
; Line 84
	add	rcx, 8
	call	QWORD PTR __imp___std_exception_destroy
	test	bl, 1
	je	SHORT $LN9@scalar
	mov	edx, 24
	mov	rcx, rdi
	call	??3@YAXPEAX_K@Z				; operator delete
$LN9@scalar:
	mov	rax, rdi
	mov	rbx, QWORD PTR [rsp+48]
	add	rsp, 32					; 00000020H
	pop	rdi
	ret	0
??_Glogic_error@std@@UEAAPEAXI@Z ENDP			; std::logic_error::`scalar deleting destructor'
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??0logic_error@std@@QEAA@$$QEAV01@@Z
_TEXT	SEGMENT
this$ = 48
__that$ = 56
??0logic_error@std@@QEAA@$$QEAV01@@Z PROC		; std::logic_error::logic_error, COMDAT
$LN6:
	push	rbx
	sub	rsp, 32					; 00000020H
	mov	rbx, rcx
	mov	rax, rdx
; File c:\program files (x86)\microsoft visual studio 14.0\vc\include\vcruntime_exception.h
; Line 65
	lea	rdx, QWORD PTR [rbx+8]
; Line 66
	lea	rcx, OFFSET FLAT:??_7exception@std@@6B@
	mov	QWORD PTR [rbx], rcx
	xor	ecx, ecx
	mov	QWORD PTR [rdx], rcx
	mov	QWORD PTR [rdx+8], rcx
; Line 67
	lea	rcx, QWORD PTR [rax+8]
	call	QWORD PTR __imp___std_exception_copy
	lea	rax, OFFSET FLAT:??_7logic_error@std@@6B@
	mov	QWORD PTR [rbx], rax
	mov	rax, rbx
	add	rsp, 32					; 00000020H
	pop	rbx
	ret	0
??0logic_error@std@@QEAA@$$QEAV01@@Z ENDP		; std::logic_error::logic_error
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??0logic_error@std@@QEAA@AEBV01@@Z
_TEXT	SEGMENT
this$ = 48
__that$ = 56
??0logic_error@std@@QEAA@AEBV01@@Z PROC			; std::logic_error::logic_error, COMDAT
$LN6:
	push	rbx
	sub	rsp, 32					; 00000020H
	mov	rbx, rcx
	mov	rax, rdx
; File c:\program files (x86)\microsoft visual studio 14.0\vc\include\vcruntime_exception.h
; Line 65
	lea	rdx, QWORD PTR [rbx+8]
; Line 66
	lea	rcx, OFFSET FLAT:??_7exception@std@@6B@
	mov	QWORD PTR [rbx], rcx
	xor	ecx, ecx
	mov	QWORD PTR [rdx], rcx
	mov	QWORD PTR [rdx+8], rcx
; Line 67
	lea	rcx, QWORD PTR [rax+8]
	call	QWORD PTR __imp___std_exception_copy
	lea	rax, OFFSET FLAT:??_7logic_error@std@@6B@
	mov	QWORD PTR [rbx], rax
	mov	rax, rbx
	add	rsp, 32					; 00000020H
	pop	rbx
	ret	0
??0logic_error@std@@QEAA@AEBV01@@Z ENDP			; std::logic_error::logic_error
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??1logic_error@std@@UEAA@XZ
_TEXT	SEGMENT
this$ = 8
??1logic_error@std@@UEAA@XZ PROC			; std::logic_error::~logic_error, COMDAT
; File c:\program files (x86)\microsoft visual studio 14.0\vc\include\vcruntime_exception.h
; Line 83
	lea	rax, OFFSET FLAT:??_7exception@std@@6B@
	mov	QWORD PTR [rcx], rax
; Line 84
	add	rcx, 8
	rex_jmp	QWORD PTR __imp___std_exception_destroy
??1logic_error@std@@UEAA@XZ ENDP			; std::logic_error::~logic_error
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??0logic_error@std@@QEAA@PEBD@Z
_TEXT	SEGMENT
_InitData$1 = 32
this$ = 64
_Message$ = 72
??0logic_error@std@@QEAA@PEBD@Z PROC			; std::logic_error::logic_error, COMDAT
; File c:\program files (x86)\microsoft visual studio 14.0\vc\include\stdexcept
; Line 28
$LN7:
	push	rbx
	sub	rsp, 48					; 00000030H
	mov	rbx, rcx
; File c:\program files (x86)\microsoft visual studio 14.0\vc\include\vcruntime_exception.h
; Line 54
	mov	BYTE PTR _InitData$1[rsp+8], 1
; File c:\program files (x86)\microsoft visual studio 14.0\vc\include\stdexcept
; Line 28
	mov	rax, rdx
; File c:\program files (x86)\microsoft visual studio 14.0\vc\include\vcruntime_exception.h
; Line 53
	lea	rcx, OFFSET FLAT:??_7exception@std@@6B@
	lea	rdx, QWORD PTR [rbx+8]
; Line 54
	mov	QWORD PTR _InitData$1[rsp], rax
	mov	QWORD PTR [rbx], rcx
	xor	ecx, ecx
	mov	QWORD PTR [rdx], rcx
	mov	QWORD PTR [rdx+8], rcx
; Line 55
	lea	rcx, QWORD PTR _InitData$1[rsp]
	call	QWORD PTR __imp___std_exception_copy
; File c:\program files (x86)\microsoft visual studio 14.0\vc\include\stdexcept
; Line 28
	lea	rax, OFFSET FLAT:??_7logic_error@std@@6B@
	mov	QWORD PTR [rbx], rax
; Line 29
	mov	rax, rbx
	add	rsp, 48					; 00000030H
	pop	rbx
	ret	0
??0logic_error@std@@QEAA@PEBD@Z ENDP			; std::logic_error::logic_error
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??_Gexception@std@@UEAAPEAXI@Z
_TEXT	SEGMENT
this$ = 48
__flags$ = 56
??_Gexception@std@@UEAAPEAXI@Z PROC			; std::exception::`scalar deleting destructor', COMDAT
$LN8:
	mov	QWORD PTR [rsp+8], rbx
	push	rdi
	sub	rsp, 32					; 00000020H
; File c:\program files (x86)\microsoft visual studio 14.0\vc\include\vcruntime_exception.h
; Line 83
	lea	rax, OFFSET FLAT:??_7exception@std@@6B@
	mov	rdi, rcx
	mov	QWORD PTR [rcx], rax
	mov	ebx, edx
; Line 84
	add	rcx, 8
	call	QWORD PTR __imp___std_exception_destroy
	test	bl, 1
	je	SHORT $LN6@scalar
	mov	edx, 24
	mov	rcx, rdi
	call	??3@YAXPEAX_K@Z				; operator delete
$LN6@scalar:
	mov	rax, rdi
	mov	rbx, QWORD PTR [rsp+48]
	add	rsp, 32					; 00000020H
	pop	rdi
	ret	0
??_Gexception@std@@UEAAPEAXI@Z ENDP			; std::exception::`scalar deleting destructor'
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?what@exception@std@@UEBAPEBDXZ
_TEXT	SEGMENT
this$ = 8
?what@exception@std@@UEBAPEBDXZ PROC			; std::exception::what, COMDAT
; File c:\program files (x86)\microsoft visual studio 14.0\vc\include\vcruntime_exception.h
; Line 89
	mov	rdx, QWORD PTR [rcx+8]
	lea	rax, OFFSET FLAT:??_C@_0BC@EOODALEL@Unknown?5exception?$AA@
	test	rdx, rdx
	cmovne	rax, rdx
; Line 90
	ret	0
?what@exception@std@@UEBAPEBDXZ ENDP			; std::exception::what
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??1exception@std@@UEAA@XZ
_TEXT	SEGMENT
this$ = 8
??1exception@std@@UEAA@XZ PROC				; std::exception::~exception, COMDAT
; File c:\program files (x86)\microsoft visual studio 14.0\vc\include\vcruntime_exception.h
; Line 83
	lea	rax, OFFSET FLAT:??_7exception@std@@6B@
	mov	QWORD PTR [rcx], rax
; Line 84
	add	rcx, 8
	rex_jmp	QWORD PTR __imp___std_exception_destroy
??1exception@std@@UEAA@XZ ENDP				; std::exception::~exception
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??0exception@std@@QEAA@AEBV01@@Z
_TEXT	SEGMENT
this$ = 48
_Other$ = 56
??0exception@std@@QEAA@AEBV01@@Z PROC			; std::exception::exception, COMDAT
; File c:\program files (x86)\microsoft visual studio 14.0\vc\include\vcruntime_exception.h
; Line 66
$LN4:
	push	rbx
	sub	rsp, 32					; 00000020H
	mov	rbx, rcx
	mov	rax, rdx
	lea	rdx, QWORD PTR [rbx+8]
	lea	rcx, OFFSET FLAT:??_7exception@std@@6B@
	mov	QWORD PTR [rbx], rcx
	xor	ecx, ecx
	mov	QWORD PTR [rdx], rcx
	mov	QWORD PTR [rdx+8], rcx
; Line 67
	lea	rcx, QWORD PTR [rax+8]
	call	QWORD PTR __imp___std_exception_copy
; Line 68
	mov	rax, rbx
	add	rsp, 32					; 00000020H
	pop	rbx
	ret	0
??0exception@std@@QEAA@AEBV01@@Z ENDP			; std::exception::exception
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??0exception@std@@QEAA@QEBD@Z
_TEXT	SEGMENT
_InitData$ = 32
this$ = 64
_Message$ = 72
??0exception@std@@QEAA@QEBD@Z PROC			; std::exception::exception, COMDAT
; File c:\program files (x86)\microsoft visual studio 14.0\vc\include\vcruntime_exception.h
; Line 53
$LN4:
	push	rbx
	sub	rsp, 48					; 00000030H
	mov	rbx, rcx
; Line 54
	mov	BYTE PTR _InitData$[rsp+8], 1
	mov	rax, rdx
	lea	rcx, OFFSET FLAT:??_7exception@std@@6B@
	lea	rdx, QWORD PTR [rbx+8]
	mov	QWORD PTR _InitData$[rsp], rax
	mov	QWORD PTR [rbx], rcx
	xor	ecx, ecx
	mov	QWORD PTR [rdx], rcx
	mov	QWORD PTR [rdx+8], rcx
; Line 55
	lea	rcx, QWORD PTR _InitData$[rsp]
	call	QWORD PTR __imp___std_exception_copy
; Line 56
	mov	rax, rbx
	add	rsp, 48					; 00000030H
	pop	rbx
	ret	0
??0exception@std@@QEAA@QEBD@Z ENDP			; std::exception::exception
_TEXT	ENDS
END
