name: Code Formatting

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  clang-format:
    name: Run clang-format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Prints the version of clang-format being used
      - name: Log clang-format version
        run: clang-format --version
        
      # Runs clang-format over the repository codebase
      - name: Check format
        run: |
          {
            find include -type f
            find tests -type f \( -name '*.cpp' -o -name '*.h' \)
          } | xargs clang-format --dry-run --Werror
