name: "Copilot Setup Steps"

on: workflow_dispatch

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - name: Install Build Dependencies
        run: sudo apt-get update && sudo apt-get install -y clang cmake make

      - name: Configure CMake (C++14)
        run: cmake --preset clang-14-debug

      - name: Configure CMake (C++20)
        run: cmake --preset clang-20-debug
